### ISSUE TITLE
Issues with CustomLanguage parameters 'your_code' and 'try_again'

### ISSUE THREAD

**Issue by tinderboxmedia** [SwissCorePy/pyTelegramBotCAPTCHA#15]
Let's take the following setup:

`languages = CustomLanguage()`
`languages.text = "text"`
`languages.try_again = "again"`
`languages.wrong_user = "wrong"`
`languages.too_short = "short"`
`languages.your_code = "code"`

'try_again' is actually not shown when it should. You keep seeing 'text' on both a wrong attempt and a manual user refresh.

'your_code' is also not shown when it should. You always see the default "Your Code:", and 'your_code' does show up but only on a wrong attempt or a manual user refresh (it is not visible on the initial captcha). However, "Your Code:" is still visible up to this point, so you actually see two lines, one time the default one, and one time the new custom one.

**Comment by SwissCorePy** [comment]
Thanks for report. We will take a look at that.

**Comment by SwissCorePy** [comment]
This is intentional.
In the last update i changed how the captcha text is put together.
`language.text` is always shown **on top**.
`language.your_code` is always shown **on the bottom**
`language.try_again` is shown **between** them if a wrong attempt happened.

In versions below 1.1.0 `language.text` was **replaced** by `language.try_again`

The reason i changed that, is because a user should always be able to know which captcha he has to solve.
If there are multible captchas in a chat at once, it could lead to confusion if they are not labeled with a user name.

When I test, it works as expected.

![Bildschirmfoto 2021-08-28 um 17 07 52](https://user-images.githubusercontent.com/51398037/131222611-af62613b-ef03-42e6-a6da-60f867836a16.png)
![Bildschirmfoto 2021-08-28 um 17 06 59](https://user-images.githubusercontent.com/51398037/131222614-63f2473b-7506-4f7d-bc55-2fe07f491c63.png)

**Comment by SwissCorePy** [comment]
Whoops referenced the wrong issue... >_<

**Comment by tinderboxmedia** [comment]
Aaaah, I found where it all goes wrong:

https://github.com/SwissCorePy/pyTelegramBotCAPTCHA/blob/4f2a2e9e8cdd8ac7749aa645264c7407a32ebbd8/pyTelegramBotCaptcha/telebot_captcha.py#L124

The moment you reference `your_code`, it will override the `try_again` as it is referenced in the wrong function.

Fix for line 124: `self._your_code = your_text + (" " if not your_text.endswith(" ") else "")`

**Comment by SwissCorePy** [comment]
> Aaaah, I found where it all goes wrong:
> 
> https://github.com/SwissCorePy/pyTelegramBotCAPTCHA/blob/4f2a2e9e8cdd8ac7749aa645264c7407a32ebbd8/pyTelegramBotCaptcha/telebot_captcha.py#L124
> 
> The moment you reference `your_code`, it will override the `try_again` as it is referenced in the wrong function.
> 
> Fix for line 124: `self._your_code = your_text + (" " if not your_text.endswith(" ") else "")`

Oh yes i see. Thank you. Its fixed!
